In [ ]:
class Node:
    
    def __init__(self, attribute_id=None, attribute_list=None, decision=None):
        self.attribute_id = attribute_id
        self.attribute_list = attribute_list
        self.children = []
        self.decision = decision
    
    def addChild(self, node):
        self.children.append(node)
        
    def getChildren():
        return self.children

    
def buildDecisionTree(df, y):
    
    if df[y].unique().shape[0] == 1:
        n=Node(decision = df[y].unique()[0])
        return
    
    df_x = df.drop([y], axis=1)
    
    if df_x.empty:
        n = Node(decision = df[y].value_counts().idxmax())
        return
    
    split_criterion = calc_gini(df, y)
    n=Node(attribute_id=split_criterion[0], attribute_list=split_criterion[1] )

In [41]:
import pandas as pd
df = pd.read_csv('./Data/electronics.csv')

if df['isBuy'].unique().shape[0] == 1:
    print(df['isBuy'].unique()[0])

df_x = df.drop(['isBuy','age','income','student'], axis=1)
df['isBuy'].value_counts().idxmax()

'yes'

In [29]:
df

            age  income student credit_rating isBuy
0         youth    high      no          fair    no
1         youth    high      no     excellent    no
2   middle_aged    high      no          fair   yes
3        senior  medium      no          fair   yes
4        senior     low     yes          fair   yes
5        senior     low     yes     excellent    no
6   middle_aged     low     yes     excellent   yes
7         youth  medium      no          fair    no
8         youth     low     yes          fair   yes
9        senior  medium     yes          fair   yes
10        youth  medium     yes     excellent   yes
11  middle_aged  medium      no     excellent   yes
12  middle_aged    high     yes          fair   yes
13       senior  medium      no     excellent    no